### ISSUE TITLE
Bot Offline?

### ISSUE THREAD

**Issue by AlbertusCraddle** [ilteoood/SiteAlert-Python#3]
Hi there,
thank you so much for your awesome @Telegram bot!  🤗 
Is the bot offline at the moment?
Can you help me with setting up an instance @digitalocean myself or add a passage to the Readme?

**Comment by ilteoood** [comment]
Hi @AlbertusCraddle,
Yes, the bot is offline since the begin of 2017.
I used to host this on my Raspberry PI, but it's time to search another place.
I'll think about it!

Thanks for the pull request,
Matteo

**Comment by ilteoood** [comment]
Hi @AlbertusCraddle,
SiteAlert is live again!
